name: Run unit tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set [ENVIRONMENT] variables
      run: |
        echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV 
        echo "OWNER_CREDENTIALS=${{ secrets.OWNER_CREDENTIALS }}" >> $GITHUB_ENV

    - name: Build
      run: cargo build --verbose
      working-directory: ./render_cdk

    - name: Run tests
      run: cargo test --verbose
      working-directory: ./render_cdk

